### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Infernio** [Infernio/wizparse#1]
wizparse should have tests and a CI - once we merge it back into WB, we'll want to carry those tests forward. Might also help other projects out.

- [x] A set of working tests -> done in 5f5af962929ee926d731c3a1a2d99664b19fc784, could always use more though
- [x] Add [Beermotor's tests](https://github.com/wrye-bash/wizparse/issues/1#issuecomment-697011117) -> done in a0ae64ab6858eb5a406bd4e106b01bc38f605f4c
- [x] A set of failing tests (to test the breaking changes and other things we *don't* want to support) -> done in a0ae64ab6858eb5a406bd4e106b01bc38f605f4c
- [x] Add some links to proprietary wizards so that people can locally test -> done in a0ae64ab6858eb5a406bd4e106b01bc38f605f4c

**Comment by Infernio** [comment]
@BeermotorWB In case you see it here - could you give us explicit permission to redistribute your BAIN wizards on https://www.afkmods.com/index.php?/topic/4987-relz-mertzs-wizbain-thread/ for CI/testing the new parser? Best to do it in a post on that thread so that we can archive and link it.

**Comment by BeermotorWB** [comment]
@Infernio sorry I'm just now seeing this.  Yes you guys always have my permission to use/distribute these and they are completely open source. 

I've published all of these on my Google Drive:

https://drive.google.com/drive/folders/1fIyAa3zV2X1QKWPdcSIwTklo1dQ71Kk2?usp=sharing

**Comment by Infernio** [comment]
Thanks :+1:

**Comment by Infernio** [comment]
Whoops, that commit should have closed this one.
