### ISSUE TITLE
Enforce position of default in Select?

### ISSUE THREAD

**Issue by Holt59** [Infernio/wizparse#12]
Currently the `selectCaseList` rule is `(caseStmt | defaultStmt)*`. I don't think it make sense to not have default as the last entry, or at least it's kind of misleading (what should happen?).

I have not checked existing scripts to see if some uses default in weird place, but I would propose to change the rule to:

```antlr4
// I don't know if the () are mandatory.
selectCaseList: (caseStmt)* (defaultStmt)?
```

Thanks for all the updates by the way :) 

**Edit:** I checked the scripts in the tests folder, the scripts I have for the interpreter and all the ones from Beermotor and none actually uses a `Default` case I think.

**Comment by Infernio** [comment]
I'm currently reworking the tests, will take a look later.
