### ISSUE TITLE
ResetAllEspmNames keyword missing

### ISSUE THREAD

**Issue by Holt59** [Infernio/wizparse#5]
In the `farmhouseChimneys.txt` script, there is a line:

```
ResetAllEspmNames
```

Which is parsed as an `Identifier` in an `expr` instead of a `Keyword`.

**Comment by Holt59** [comment]
Okay, I'm stupid, I thought this was some kind of priority issue but it's just the keyword missing in the `Keyword` rule...

**Comment by Holt59** [comment]
Here is the (current) list of keyword I use in my modified [`wizard.g4`](https://github.com/Holt59/bain-wizard-interpreter/blob/master/wizard/antlr4/wizard.g4)<sup>1</sup> - My tests should break if a `Keyword` is missing in one of the test scripts:

```antlr4
Keyword:
	'DeSelectAll'
	| 'DeSelectAllPlugins'
	| 'DeSelectAllEspms'
	| 'DeSelectPlugin'
	| 'DeSelectEspm'
	| 'DeSelectSubPackage'
	| 'Note'
	| 'RenamePlugin'
	| 'RenameEspm'
	| 'RequireVersions'
	| 'ResetPluginName'
	| 'ResetEspmName'
	| 'ResetAllEspmNames'
	| 'ResetAllPlugins'
	| 'SelectAll'
	| 'SelectAllPlugins'
	| 'SelectAllEspms'
	| 'SelectPlugin'
	| 'SelectEspm'
	| 'SelectSubPackage';
```

<sup>1</sup> I currently keep a custom version in my repository but I'll remove it when this version get everything fixed.

**Comment by Infernio** [comment]
NB: `ResetAllPlugins` does not exist, the right keyword is `ResetAllPluginNames`.

**Comment by Holt59** [comment]
> 
> 
> NB: `ResetAllPlugins` does not exist, the right keyword is `ResetAllPluginNames`.

Thanks, looks like I never encountered it in all the mods I tested 🙃

**Comment by Infernio** [comment]
I added the `*Plugin*` versions of all `*Espm*` keywords in https://github.com/wrye-bash/wrye-bash/commit/3426384083bd5d7c61d42730ed7fa9c5629bc2db, so they haven't been out for very long. Especially since almost no new wizards get written these days.

**Comment by Holt59** [comment]
Ah, nice to know. Shame this is not use more... There are a few things I found annoying in the scripting language but overall it's pretty nice.

I've made a (I think) fully functional installer for Mod Organizer 2 based on my interpreter and a slightly modified version of your grammar which might be included in the next MO2 release, so maybe people will start to write script again 🙃

**Comment by Infernio** [comment]
It's definitely superior to FOMOD, simply by virtue of *having* a specification, buggy and incomplete as it is :stuck_out_tongue:
