### ISSUE TITLE
Is test.txt semantically valid?

### ISSUE THREAD

**Issue by Holt59** [Infernio/wizparse#6]
According to the README (eh... ), `Note` should be followed by something that evaluates to a string. 

In `test.txt`, it contains `3 + 6 * 2`, which obviously is not a string. Is this a simple mistake when writing the test or is this a test that actually passes with the current interpreter?

**Comment by Infernio** [comment]
The implementation is `'- %s\n' % note`, so literally anything that can be converted into a string is accepted by the current parser. If that *should* be the case is a different question, but I would lean towards 'yes' here actually.

**Comment by Holt59** [comment]
I just tested and indeed the current version of Wrye Bash convert everything to string.
