### ISSUE TITLE
Origin of test files?

### ISSUE THREAD

**Issue by Holt59** [Infernio/wizparse#7]
In the `tests` folder you have `.license` files that contain link to the mod but when I follow the link and try to download the archives, most of the time I cannot found the one with the script you have in `tests`.

For instance, the main installer for "Majestic Mountain" is not the one in `tests` (the one currently on Nexus actually breaks with Wrye Bash).

Where do the script files in `tests` come from?

**Comment by Infernio** [comment]
Many mods eventually drop their wizards in later versions, so you'll have to look through all files in the `Files` section. For Majestic Mountains, the old file from version 1.3 has the wizard.
